name: Java CI with Maven - Test and package

on:
  pull_request:
    branches: [ main ]  # Se déclenche quand une pull request est ouverte vers la branche main

jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build and test with Maven
        run: mvn -B package --file pom.xml
