name: Bonjour
on:[push]  

jobs:
  Salutations:  # Nom du job
    runs-on: ubuntu-latest  # OS où s'exécute le job
    steps:
      - name: Hello  # Première tâche : saluer
        env:
          personneASaluer: 'Mon voisin Totoro'
        run: echo "Bonjour ${personneASaluer}"

      - name: L'heure de salutation  # Deuxième tâche : afficher l'heure
        run: echo "L'heure était $(date)."
